### ISSUE TITLE
ace.Load doesn't seem to work!

### ISSUE THREAD

**Issue by nelsonpecora** [yosssi/martini-acerender#1]
When I `go get` this package, it gives me this error:

`../../yosssi/martini-acerender/render.go:39: undefined: ace.Load`

**Comment by yosssi** [comment]
Oh, please update Ace by executing `go get -u github.com/yosssi/ace`.
I changed Ace's API name from "ParseFiles" to "Load".

**Comment by nelsonpecora** [comment]
Ah, cool. Thanks!
