### ISSUE TITLE
Is acerender stable?

### ISSUE THREAD

**Issue by dariusc93** [yosssi/martini-acerender#3]
Hi,

I am moving from gold to ace, and I originally used rendergold for martini, I would like to know if this is stable and have similar functionality or is this in development and should be avoided until it is stable? If it is, in fact, stable could you provide documentations on this, what options are available for used, etc?

**Comment by yosssi** [comment]
@dariusc93 Thanks for using Gold and Ace. For now, Ace and Acerender are in development. I'm trying to make them maintain their backward compatibility as possible as I can but they don't actually. I'm now considering when to make Ace and Acerender stable. So, there are a few risks when using Ace and Acerender but you can avoid the risks by fixing the revision of Ace and Acerender by using Go package manager like [gom](https://github.com/mattn/gom) or forking them to your repositories. I will let you know when I decide when to make Ace and Acerender stable. Thanks.
