### ISSUE TITLE
pass struct into renderer

### ISSUE THREAD

**Issue by avdept** [yosssi/martini-acerender#4]
Is there any way to pass struct, to use its fields in view(e.g. rails ActiveRecord model object) ?

**Comment by yosssi** [comment]
Yes, you can pass a `struct` to `Render.HTML`. Its third parameter is data (a `struct`, `map`, `slice` and so on) which can be used in views.

**Comment by avdept** [comment]
Thanks, already figured that out. The only notice(maybe its obvious for others, but i'm new to golang) fields in struct should be public(capitalized)
